### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zirconcug** [mmueller13/Detrital-UPb-and-TE#1]
when i run section 2.2 on Mac, there is an error: Javascript Error: Can't find variable: IPython

in section 3.1, Plot results of Stacey-Kramers discordance, there is an error: 
Cell In[10], line 61
     58 # Plot the points and connect them with lines
     59 axes[1].scatter(Xs386_data[~zero_mask], Ys76_data[~zero_mask], color='dimgray', edgecolors='black', linewidths=0.5, 
     60                 label=f'Analysis without S-K Distance', s=15, zorder=3)
---> 61 scatter_plot = axes[1].scatter(Xs386_data[~zero_mask], Ys76_data[~zero_mask], c=SKdist[~zero_mask], cmap='Purples_r',
     62                                norm=mcolors.LogNorm(vmin=0.1, vmax=1000),
     63                                edgecolors='black', linewidths=0.5,
     64                 label=f'Uncorrected Analysis', zorder=4)
     66 # Plot intersection lines
     67 for i in range(len(x1_data)):
     68     #color = plt.cm.PuRd_r(i / len(x1_data+2))
NameError: name 'SKdist' is not defined

in section 3.2,
Cell In[12], line 33
     31 plt.subplot(1, 2, 1)
     32 plt.plot(np.log(X86), np.log(Y76), label='Concordia', color='red')
---> 33 plt.scatter(np.log(X86tMyr), np.log(Y76tMyr), color='red', s=10)  # Mark specified points in red
     34 plt.plot(ln_x_values, ln_y_values, label='185 Ma isochron', color='black') # label=f'ln(y) = {slope:.2f}ln(x) + {np.log(np.abs(b)):.2f}'
     35 scatter2 = plt.scatter(np.log(Xs386), np.log(Ys76), c=aitchison_distances_min, cmap=cmap, label='Analyses',  edgecolors='black', linewidth=0.5)  # Scatter plot of data in black
NameError: name 'X86tMyr' is not defined

**Comment by mmueller13** [comment]
The error message "Javascript Error: Can't find variable: IPython" suggests that there might be an issue with the JavaScript environment. Troubleshooting may resolve the issue: check IPython installation, restart the Kernel, check browser compatibility if using IPython in a web-based environment (such as Jupyter Notebook or JupyterLab), update IPython and check dependencies. 

In section 3.1, there is a line missing at the top of the cell:
`SKdist = df_Discordance['SK_lower_distance'][:num_rows]`

In section 3.2, there were several lines missing from the first cell:
```
tMyr = np.array([75e6, 100e6, 200e6, 350e6, 500e6, 750e6, 1000e6, 2000e6, 3000e6, 4000e6])
X86tMyr = 1 / (np.exp(lambda238 * tMyr) - 1) # 206/238 ratio at specified time
Y76tMyr = (1 / rat85) * (np.exp(lambda235 * tMyr) - 1) / (np.exp(lambda238 * tMyr) - 1) # 207/206 ratio at specified time
age = tMyr / 1e6
```
An updated version of the notebook is now in the repository. Thanks

**Comment by zirconcug** [comment]
这是来自QQ邮箱的自动回复邮件。你好，我已收到你的邮件，将尽快给你回复。
